### ISSUE TITLE
gpu not removed during boot

### ISSUE THREAD

**Issue by scurrvy2020** [pedro00dk/nvidia-exec#2]
I installed your script.  However, it doesn't seem to actually remove the gpu during boot.  I tried changing the systemd service to use `nvx off-kill` and the gpu still loaded on boot.

I also tried adding Before = gdm.service to nvx.service [Unit] section and it caused my boot to hang, so it may not be gdm causing the issue.

I can execute `nvx off-kill` in the terminal after boot and gdm is killed and reloaded without the gpu.

Your implementation looks a bit more sophisticated than nvidia-xrun so I'm not sure why nvidia-xrun-pm.service works to remove my gpu and this doesn't.

**Comment by pedro00dk** [comment]
Hi @scurrvy2020, could you please provide the systemd logs for nvx service.
If possible, with the unchanged service file.

```shell
$ systemctl status nvx.service.
```

**Comment by scurrvy2020** [comment]
```

Feb 16 18:21:53 hpCTO sudo[678]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Feb 16 18:21:53 hpCTO sudo[678]: pam_unix(sudo:session): session closed for user root
Feb 16 18:21:53 hpCTO nvx[405]: # turn off gpu
Feb 16 18:21:53 hpCTO sudo[695]:     root : PWD=/ ; USER=root ; COMMAND=/usr/bin/lshw -json
Feb 16 18:21:53 hpCTO sudo[695]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
Feb 16 18:21:54 hpCTO sudo[695]: pam_unix(sudo:session): session closed for user root
Feb 16 18:21:54 hpCTO nvx[405]: -- pci "PCI bridge - Sunrise Point-LP PCI Express Root Port #1" -> 0000:00:1c.0
Feb 16 18:21:55 hpCTO nvx[405]:    -- device remove "3D controller - GP108M [GeForce MX150]" -> 0000:01:00.0
Feb 16 18:21:55 hpCTO sudo[914]:     root : PWD=/ ; USER=root ; COMMAND=/usr/bin/tee /sys/bus/pci/devices/0000:01:00.0/remove
Feb 16 18:21:55 hpCTO sudo[914]: pam_unix(sudo:session): session opened for user root(uid=0) by (uid=0)
```

It doesn't give any errors, but it also doesn't complete the task. 

I disabled nvidia-persistenced.service and it seems to be working to stop the card on boot and I am able to turn the card on and off with your utility.

**Comment by pedro00dk** [comment]
I'm my system, that `nvidia-persistenced.service` is disabled by default. I do not remember ever tweaking it.
I did enable it to try reproducing the same issue as you but in my case, the `nvidia-persistenced.service` was the one who failed.

Initially, I just tested enabling `nvidia-persistenced.service` with `nvx.service` disabled.
I expected it to fail because the Nvidia modules are blacklisted, but the service is successful, and it cause a couple of  Nvidia modules to load.

Then I tested with both services enabled, in my case, the one who fails in the `nvidia-persistenced.service`, not `nvx.service`

```
Feb 17 07:59:30 pedro systemd[1]: Starting NVIDIA Persistence Daemon...
Feb 17 07:59:30 pedro nvidia-persistenced[334]: Started (334)
Feb 17 07:59:31 pedro nvidia-persistenced[334]: Failed to query NVIDIA devices. Please ensure that the NVIDIA device fi>
Feb 17 07:59:31 pedro nvidia-persistenced[334]: Shutdown (334)
Feb 17 07:59:31 pedro nvidia-persistenced[331]: nvidia-persistenced failed to initialize. Check syslog for more details.
Feb 17 07:59:31 pedro systemd[1]: nvidia-persistenced.service: Control process exited, code=exited, status=1/FAILURE
Feb 17 07:59:31 pedro systemd[1]: nvidia-persistenced.service: Failed with result 'exit-code'.
Feb 17 07:59:31 pedro systemd[1]: Failed to start NVIDIA Persistence Daemon.
```

I think I was just lucky though. They run at the same time, and if `nvidia-persistenced.service` would be faster, it probably would cause `nvx.service` to hang.

![image](https://user-images.githubusercontent.com/7131232/154471995-8791becd-0941-48ea-a162-975706784279.png)

Anyway, I think it is possible could make one service depend on the other, but it does not make sense to operate the Nvidia card during boot when you are trying to disable it as well.

It also seems that `nvidia-persistenced.serice` is not that important, and can easily be enabled manually. So maybe another option is to add it as an option to nvx.
https://download.nvidia.com/XFree86/Linux-x86_64/510.54/README/nvidia-persistenced.html

For now, I will just put a note on the README, and check if I can disable Nvidia services during the installation.
