### ISSUE TITLE
nvidia-exec: graphical glitches and hangs when closing Steam

### ISSUE THREAD

**Issue by CygnusTerminal** [pedro00dk/nvidia-exec#7]
Hi, i am having issues with nvidia-exec and Steam. I am having graphical issues inside Steam (parts of the screen flickering black) It also gets stuck when trying to exit steam. Killing steam with `nvx kill` works, but then gets stuck at
-- device remove "VGA compatible controller - TU117M" -> 0000:01:00.0

**Comment by pedro00dk** [comment]
@CygnusTerminal 

It is probably not because of steam. When that happens again, you can check with processes that are trying to use the GPU with `nvx ps`. That happens to me a lot with google chrome.

About the flickering issue, I'm not sure I can do anything about it. In my case, although I use the GPU for mostly for computing purposes, I have sporadic tearing issues when playing games. I believe that is because of the state of the nvidia-driver support on linux, and that will only get better with newer driver releases.

If nvx is not working for you, I suggest you try nvdia-xrun (requires more setup and it is a bit anoying to run, but has the best performance), or bumblebee + primusrun + primusvk (has a performance penalty but it is easy to setup).

**Comment by CygnusTerminal** [comment]
> @CygnusTerminal
> 
> It is probably not because of steam. When that happens again, you can check with processes that are trying to use the GPU with `nvx ps`. That happens to me a lot with google chrome.
> 
> About the flickering issue, I'm not sure I can do anything about it. In my case, although I use the GPU for mostly for computing purposes, I have sporadic tearing issues when playing games. I believe that is because of the state of the nvidia-driver support on linux, and that will only get better with newer driver releases.
> 
> If nvx is not working for you, I suggest you try nvdia-xrun (requires more setup and it is a bit anoying to run, but has the best performance), or bumblebee + primusrun + primusvk (has a performance penalty but it is easy to setup).

Hi, i prefer your approach since it's the easiest. I'll try to debug the issues so i can maybe help improve what we can.
